# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates



windowrule = match:class ^(org\.kde\.kdeconnect\.app)$, workspace 9 silent

windowrule = match:class ^(v2rayN)$, workspace 9 silent
